package main;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Point2D;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;

import javax.swing.JPanel;

import HUD.GUI;
import HUD.HUD;
import objects.BootsObject;
import objects.Bullet;
import objects.DoorObject;
import objects.GameObject;
import objects.KeyObject;
import objects.Oldman;
import objects.Player;
import objects.Slime;
import objects.Tank;
import objects.EnemyTank;
import objects.TreeObject;
import objects.Wall;
import utils.ObjectManager;
import utils.TileManager;

// implements Runnable is for the gameThread
public class GamePanel extends JPanel implements Runnable {
	
	// SCREEN SETTINGS
	final int originalTileSize = 16;
	final int scale = 3; // scale up the sprite since 16x16 is going to be very small
	
	public final int tileSize = originalTileSize * scale;
	
	public final int maxScreenCol = 20;
	public final int maxScreenRow = 12;
	public final int screenWidth = maxScreenCol * tileSize; // 768 pixels
	public final int screenHeight = maxScreenRow * tileSize; // 576 pixels
	
	public float camX, camY;
	
	// WORLD SETTINGS
	public final int maxWorldCol = 45;
	public final int maxWorldRow = 43;
	public final int worldWidth = maxWorldCol * tileSize;
	public final int worldHeight = maxWorldRow * tileSize;
	
	int FPS = 60;
	
	public KeyHandler keyHandler = new KeyHandler(this);
	Thread gameThread;
	
	// PLAYER
	public Player player;
	public Tank tank;
	public int score = 0;
	
	// DRAW TILES AND SET INVISIBLE WALLS
	TileManager tileManager = new TileManager(this);
	
	// COLLISION BLOCKS
	public final CopyOnWriteArrayList<GameObject> gameObjects = new CopyOnWriteArrayList<>(); // CopyOnWriteArrayList solves the ConcurrentModificationException
	
	// SOUND
	Sound sound = new Sound();
	boolean playMusic = true;
	boolean playSFX = true;
	
	// HUD
	public HUD hud = new HUD(this);
	public ArrayList<GUI> GUIList = new ArrayList<>();
	
	// GAME STATE
	public enum GameState {
		paused,
		play,
		inDialogue,
		inMenu,
		gameOver
	}
	public GameState gameState;
	
	public GamePanel() {
		// INITIATE GAME
		this.setPreferredSize(new Dimension(screenWidth, screenHeight));
		this.setBackground(Color.black);
		this.setDoubleBuffered(true);
		
		this.addKeyListener(keyHandler);
		this.setFocusable(true); // with this, this GamePanel can be 'focused' to receive key input
		
		player = new Player(new Point2D.Double(0, 0) , this, keyHandler);
//		tank = new Tank(new Point2D.Double(19 * tileSize, 30 * tileSize) , this, keyHandler);
		tank = new Tank(new Point2D.Double(19 * tileSize, 33 * tileSize) , this, keyHandler);
				
		this.gameState = GameState.inMenu;
		
		tileManager.loadMap("map03.txt");
		
		playMusic("BlueBoyAdventure.wav");
		
		ObjectManager.loadGamePanel(this);
		ObjectManager.addObjects();
	}
	
	public void addGameObject(GameObject object) {
		synchronized (gameObjects) {
			gameObjects.add(object);
		}
//		this.gameObjects.add(object);
	}
	
	public void removeGameObject(GameObject object) {
		// apparently, for some reason if the object you're removing is NOT the second last object in the arraylist
		// this exception will occur: Exception in thread "Thread-0" java.util.ConcurrentModificationException
		// unreal
		
		// FIRST attemp
//		gameObjects.remove(object);
		
		// SECOND attempt
//		Iterator<GameObject> iterator = gameObjects.iterator();
//		while (iterator.hasNext()) {
//		    GameObject nextObject = iterator.next();
//		    if (nextObject.equals(object)) {
//		    	iterator = null;
//		        iterator.remove(); // Safe to remove using Iterator
//		    }
//		}
		
		// THIRD attempt
		// a different error is caught but at least the game is not freezed... most of the time
		new Thread(new Runnable() {
		    public void run() {
		        //Do whatever
		    	gameObjects.remove(object);
		    }
		}).start();
		
		// FOURTH attempt
		// this is generated by chatGPT. It resolves NOTHING btw
//		List<GameObject> copy = new ArrayList<>(gameObjects);
//		for (GameObject gameObject : copy) {
//            if (gameObject.equals(object)) {
//                gameObjects.remove(gameObject);
//            }
//        }
	}
	
	public void startGameThread() {
		gameThread = new Thread(this);
		gameThread.start();
	}
	
	// AABB collision detection
	public boolean checkCollision(GameObject player, GameObject block) {
		final float playerX = (float) (player.getPosition().getX() + player.getHitbox().getX());
		final float playerY = (float) (player.getPosition().getY() + player.getHitbox().getY());
		final float playerWidth = player.getHitbox().width;
		final float playerHeight = player.getHitbox().height;
		
		final float blockX = (float) (block.getPosition().getX() + block.getHitbox().getX());
		final float blockY = (float) (block.getPosition().getY() + block.getHitbox().getY());
		final float blockWidth = block.getHitbox().getWidth() == 0 ? block.getWidth() : block.getHitbox().width;
		final float blockHeight = block.getHitbox().getHeight() == 0 ? block.getHeight() : block.getHitbox().height;
			
		return playerX < blockX + blockWidth &&
				playerX + playerWidth > blockX &&
				playerY < blockY + blockHeight &&
				playerY + playerHeight > blockY;
//		return playerX < block.getPosition().x + block.getWidth() &&
//				playerX + playerWidth > block.getPosition().x &&
//				playerY < block.getPosition().y + block.getHeight() &&
//				playerY + playerHeight > block.getPosition().y;
	}
	
	@Override
	public void run() {
		
		double drawInterval = 1000000000/FPS;
		double delta = 0;
		long lastTime = System.nanoTime();
		long currentTime;
		
		while (gameThread != null) {
			
			currentTime = System.nanoTime();
			
			delta += (currentTime - lastTime) / drawInterval;
			
			lastTime = currentTime;
			
			// máy mạnh -> hàm này được thực hiện nhiều lần -> update được gọi nhiều
			// máy yếu -> (currentTime - lastTime) lớn -> delta tăng nhanh hơn mỗi lần gọi -> update được gọi nhiều
			// ==> số lần gọi update() giữa máy mạnh và máy yếu như nhau, không cần phải truyền dt vào object nữa
			
			// TUY NHIÊN, nếu muốn chính xác đến từng số thập phần (tốc độ bằng nhau giữa máy mạnh và yếu)
			// người ta sẽ truyền delta time vào object
			if (delta >= 1) {
				update();
				repaint();
				delta--;
			}
		}
	}
	
	public void update() {
		
		if (gameState != GameState.play) return;
		
		// không cần phải truyền delta time vào
		
		tank.update();
		
		for (GameObject object : gameObjects) {
			if (object instanceof Oldman) {
				((Oldman) object).update();
			} else if (object instanceof Slime) {
				((Slime) object).update();
			} else if (object instanceof Bullet) {
				((Bullet) object).update();
			} else if (object instanceof EnemyTank) {
				((EnemyTank) object).update();
			}
		}
		
		for (GUI object : GUIList) {
			object.update();
		}
		
	}
	
	public void paintComponent(Graphics g) {
		super.paintComponent(g);
		
		Graphics2D g2 = (Graphics2D)g; // change Graphics to Graphics2D
		
		if (gameState != GameState.inMenu && gameState != GameState.gameOver) {
			// set the camera to follow the player
			camX = (float) (tank.getPosition().getX() - screenWidth / 2);
			camY = (float) (tank.getPosition().getY() - screenHeight / 2);
			
			g2.translate(-camX, -camY);
			
			// drawing the blue "ocean" background
			g2.setColor(Color.decode("#0090e6"));
			g2.fillRect((int) camX, (int) camY, screenWidth, screenHeight);
			
			drawingObjects(g2);
		}
		
		hud.draw(g2);
		
		for (GUI object : GUIList) {
			object.draw(g2);
		}
		
		g2.dispose();
	}
	
	public void drawingObjects(Graphics2D g2) {

		// some objects get added in here when player's y < that object's y (meaning the player is behind the object)
		ArrayList<GameObject> priorityObjects = new ArrayList<>();
		
		for (GameObject object : gameObjects) {
			if (object instanceof KeyObject || object instanceof DoorObject || object instanceof BootsObject || object instanceof Wall) {
				object.draw(g2);
			} else if (object instanceof Bullet || object instanceof EnemyTank) {
				object.draw(g2);
			} else if (object instanceof TreeObject || object instanceof Oldman) {
				if (tank.getPosition().getY() < object.getPosition().getY() - object.getHitbox().y) {
					priorityObjects.add(object);					
				} else {
					object.draw(g2);
				}
			}
			else if (object instanceof Slime) {
				if (tank.getPosition().getY() + tank.getHitbox().height< object.getPosition().getY() + object.getHitbox().y + object.getHitbox().height) {
					priorityObjects.add(object);					
				} else {
					object.draw(g2);
				}
			}
			else {
				tileManager.drawSingle(g2, (int) object.getPosition().getX(), (int) object.getPosition().getY());
			}
		}
		
		tank.draw(g2);
		
		for (GameObject object : priorityObjects) {
			object.draw(g2);
		}
		
		priorityObjects.clear();
	}
	
	public void switchGameState(GameState newGameState) {
		gameState = newGameState;
	}
	
	public void playMusic(String fileName) {
		if (!playMusic) return;
		sound.setFile(fileName);
		sound.play();
		sound.loop();
	}
	
	public void stopMusic(String fileName) {
		sound.stop();
	}
	
	public void playSFX(String fileName) {
		if (!playSFX) return;
		sound.setFile(fileName);
		sound.setVolume(0.2f);
		sound.play();
	}
}
